### Get board
GET http://localhost:3001/boards

### Create column
POST http://localhost:3001/boards/1/columns
Content-Type: application/json

{
  "title": "Todo"
}

### Get columns
GET http://localhost:3001/boards/1/columns

### Create task
POST http://localhost:3001/boards/1/columns/dc94ffb0-6d4e-45f5-ac5b-a0677bbcc00b/tasks
Content-Type: application/json

{
  "title": "Backend",
  "description": "Implement CRUD"
}